<a href="https://colab.research.google.com/github/crce9830ecs-lang/aiml_labs/blob/main/ML_LAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

4-08

In [2]:
print("Oops, I did it again!")

Oops, I did it again!


In [11]:
#creating arrays
import numpy as np
arr = np.array([4,5,6,3,2,1])
print(arr)

b = np.arange(1,11) #give a range and then function will create an array
print(b)

c = np.linspace(0,1,5)
print(c)    #0: The starting point of the sequence.1: The end point of the sequence (included by default).5: The total number of elements to generate.

[4 5 6 3 2 1]
[ 1  2  3  4  5  6  7  8  9 10]
[0.   0.25 0.5  0.75 1.  ]


In [14]:
# matrix operation
a =np.array(([1,2],
             [3,4]))
b =np.array(([2,2],
             [4,4]))
print(a+b)
print(a-b)
print(a*b) #element wise multiplication
print(a@b) # matix multiplication

[[3 4]
 [7 8]]
[[-1  0]
 [-1  0]]
[[ 2  4]
 [12 16]]
[[10 10]
 [22 22]]


In [24]:
#assignment
# weather data of july days in udupi,
# - find hottest and clodest day
# - ang temp
# - dates above 35 deg cel
import numpy as np

weather = np.array([
    [1, 26], [2, 28], [3, 28], [4, 29], [5, 30],
    [6, 30], [7, 30], [8, 30], [9, 31], [10, 30],
    [11, 30], [12, 30], [13, 30], [14, 31], [15, 31],
    [16, 30], [17, 27], [18, 29], [19, 29], [20, 27],
    [21, 29], [22, 26], [23, 29], [24, 30], [25, 29],
    [26, 29], [27, 30], [28, 28], [29, 29], [30, 30],
    [31, 30]
])

index = np.argmin(weather[:,1])
date = weather[index, 0]
temp = weather[index, 1]
print(f"hottest day is on {date} with a temperature of {temp}")

index = np.argmax(weather[:,1])
date = weather[index, 0]
temp = weather[index, 1]
print(f"coldest day is on {date} with a temperature of {temp}")

avg = np.mean(weather[:,1])
print(f"the avg temp is {avg}")

if ((weather[:,1]) > 35).any():
  print((weather[0,0]))

hottest day is on 1 with a temperature of 26
coldest day is on 9 with a temperature of 31
the avg temp is 29.193548387096776
